# Generated by Django 4.1.3 on 2022-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('storyline', models.TextField(blank=True, verbose_name='О чем статья')),
                ('text', models.TextField(blank=True, verbose_name='Статья')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('number_rating', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
            ],
        ),
    ]
