# Generated by Django 4.1.3 on 2022-11-15 13:22

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название услуги')),
                ('image', models.ImageField(null=True, upload_to=services.models.service_image_file_path, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Список услуг',
            },
        ),
    ]
