# Generated by Django 4.1.3 on 2022-11-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_rename_service_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('storyline', models.CharField(max_length=200, verbose_name='О чем статья')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('number_rating', models.IntegerField(default=0, verbose_name='Количество оценок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.service')),
            ],
        ),
    ]
