# Generated by Django 4.1.3 on 2022-11-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='текст', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='storyline',
            field=models.TextField(verbose_name='О чем статья'),
        ),
    ]
