# Generated by Django 4.1.3 on 2022-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_text_alter_article_storyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='storyline',
            field=models.TextField(blank=True, verbose_name='О чем статья'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name='Статья'),
        ),
    ]
