# Generated by Django 4.1.3 on 2022-11-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_storyline_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
        migrations.RemoveField(
            model_name='article',
            name='number_rating',
        ),
        migrations.RemoveField(
            model_name='article',
            name='service',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
