# Generated by Django 4.1.3 on 2022-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_active_remove_article_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='article',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата написания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='number_rating',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name='Статья'),
        ),
    ]
