# Generated by Django 4.1.3 on 2022-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_active_article_avg_rating_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='service',
            field=models.CharField(default='aasd', max_length=50, verbose_name='Тематика (сервис)'),
            preserve_default=False,
        ),
    ]
