# Generated by Django 4.1.3 on 2022-11-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=20, verbose_name='Название услуги')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Список услуг',
            },
        ),
    ]
