# Generated by Django 4.1.3 on 2022-11-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_description_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='name',
        ),
    ]
